По предыдущим комментам:

В XHR сделал resolve только 200 статуса, остальное в reject.
Убрал try catch и перенес обработку результата запроса логина и регистрации на обработку промисов и на лиснеры в контроллерах. Теперь ошибка показывается :)
Сделал для попапа ошибки отдельный класс
Убрал вроде всю работу с сокетами в отдельные утилки

вроде проверял, но, надеюсь, попутно ничего не уронил :)

### [PullRequest](https://github.com/TheRealMagic/middle.messenger.praktikum.yandex/pull/16)
